#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=40G
#SBATCH --time=24:00:00
#SBATCH --partition=aa100
#SBATCH --gres=gpu:1
#SBATCH --account=ucb437_asc1
#SBATCH --mail-type=ALL
#SBATCH --mail-user="rey.koki@colorado.edu"

unset SLURM_MEM_PER_NODE
unset SLURM_MEM_PER_GPU

module purge
module load cuda/11.8
module load cudnn/8.6

source /curc/sw/anaconda3/2023.09/bin/activate
conda activate alpine

python model.py $EXP_NUM
exit 0
